services:
  postgres:
    ports:
      - '15432:5432'

  redis:
    ports:
      - '16379:6379'

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - '3003:3003'

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    ports:
      - '3004:3004'
